Initial Features
vgeruso/nestjs4noobs pull request #1
Opened 2024-09-12 22:41 UTC by vgeruso

## List

- Primeiros passos
- Controllers
- services/providers
- modules

2024-09-16 12:17 UTC, joaovjo requested changes
Realizar correções

2024-09-16 12:17 UTC, joaovjo commented on README.md
> +## Autores
Trocar para "Contribuidores"

2024-09-16 12:17 UTC, joaovjo commented on README.md
> +- **Victor Geruso Gomes** - _Engenheiro de Software [Dev Backend]_ - **[Twitter](https://x.com/vgeruso)**
Adicionar "Autor", adicionar outras redes sociais

2024-09-16 12:17 UTC, joaovjo commented on src/content/1-introducao.md
> +O Nest de acordo com a documentação oficial, é um framework para construção de aplicações Node.js do lado do servidor eficientes e escalonáveis. Usando JavaScript progressivo, é construido e possui s
Linha 3, nome incorreto, trocar para NestJS

2024-09-16 12:17 UTC, joaovjo commented on src/content/1-introducao.md
> +O Nest de acordo com a documentação oficial, é um framework para construção de aplicações Node.js do lado do servidor eficientes e escalonáveis. Usando JavaScript progressivo, é construido e possui s
Informar que NestJS é um framework opinativo

2024-09-16 12:17 UTC, joaovjo commented on src/content/1-introducao.md
> +Por debaixo dos panos, o nosso framework usa como padrão o Express, mas pode ser facilmente configurado para usar o Fastfy. Sendo inspirado no framework frontend Angular o nest fornece uma arquitetur
Está escrito "nest", trocar para "NestJS"

2024-09-16 12:17 UTC, joaovjo commented on src/content/1-introducao.md
> +Por debaixo dos panos, o nosso framework usa como padrão o Express, mas pode ser facilmente configurado para usar o Fastfy. Sendo inspirado no framework frontend Angular o nest fornece uma arquitetur
Corrigir gramática: "Fastfy" para "Fastify"

2024-09-16 12:17 UTC, joaovjo commented on src/content/1-introducao.md
> +Por debaixo dos panos, o nosso framework usa como padrão o Express, mas pode ser facilmente configurado para usar o Fastfy. Sendo inspirado no framework frontend Angular o nest fornece uma arquitetur
Corrigir gramática: "testaveis" para "testáveis"

2024-09-16 12:17 UTC, joaovjo commented on src/content/1-introducao.md
> +Por debaixo dos panos, o nosso framework usa como padrão o Express, mas pode ser facilmente configurado para usar o Fastfy. Sendo inspirado no framework frontend Angular o nest fornece uma arquitetur
Corrigir gramática: "escalaveis" para "escaláveis"

2024-09-16 12:17 UTC, joaovjo commented on src/content/1-introducao.md
> +pré requisitos para o uso e instalação do Nest:
Correção gramatical: "Pré-requisitos", "NestJS"

2024-09-16 12:17 UTC, joaovjo commented on src/content/1-introducao.md
> +Existem diversas formas para iniciar um projeto Nest, mas o mais básico e utilizado (por ser mais prático) é com o Nest CLI, para isso temos que instala-lo de forma global em nossa maquina com o segu
Correção gramatical: "NestJS", "instalá-lo", "máquina"

2024-09-16 12:17 UTC, joaovjo commented on src/content/1-introducao.md
> +npm i -g @nestjs/cli
Adicione também métodos de instalação usando yarn, pnpm e bun

2024-09-16 12:17 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +Para criar um projeto é simples basta executar:
Correção gramatical: "é simples, basta executar:"

2024-09-16 12:17 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +O Nest CLI irá realizar uma pergunta básica de configuração relacionado ao gerenciador de pacotes que irá ser usado por padrão, aqui eu escolhi o `npm` mas fique a vontado para escolher o seu. Após a
Correção gramatical: "npm, mas", "vontade".

2024-09-16 12:17 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +No repositório que foi criado com o processo, são gerados arquivos de configuração relacionadas a algumas ferramentas vinculadas a aplicação, e o diretório `src` composto por arquivos escenciais para
Correção gramatical: "à algumas", "essenciais"

2024-09-16 12:17 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +| `app.controller.spec.ts` | Modulo de teste do controller                                                                             |
Correção gramatical: "Módulo"

2024-09-16 12:17 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +Para criar uma instancia do aplicativo Nest, a classe principal `NestFactory` que expõe métodos estaticos e permitem a criação da instancia do aplicativo. o metodo `create()` retorna um objeto que pr
Correção gramatical: "instância", "estáticos", "método".

2024-09-16 12:17 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +Para criar uma instancia do aplicativo Nest, a classe principal `NestFactory` que expõe métodos estaticos e permitem a criação da instancia do aplicativo. o metodo `create()` retorna um objeto que pr
Após a palavra "iniciado", retire a vírgula. o "e" se refere a uma continuação de pensamento, não é necessário a vírgula nesse caso

2024-09-16 12:17 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +O sistema irá executar uma transpilação do TypeScript e excutar os endpoits criados imprimindo na tela os ativos:
Correção gramatical: "endpoints"

2024-09-16 12:17 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +O sistema irá executar uma transpilação do TypeScript e excutar os endpoits criados imprimindo na tela os ativos:
O TypeScript é instalado e configurado no Node.js globalmente quando o Nest CLI é instalado ou é necessário que o desenvolvedor o faça? Informe sobre isso no instalacao.md

2024-09-16 12:17 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +Agora basta acessar em seu navegador o [http://localhost:3000/](http://localhost:3000/), você deverá ver a mensagem `Hello World!` na tela.
Única forma de ver o resultado é com o navegador? Ou existem programas ou extensões que permitem fazer isso? Se sim, quais? Informe os links como opções de visualização

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +Os controllers são classes responsáveis por receber solicitações e retornar respostas ao cliente atrevés do protocolo `HTTP`.
O que é o "protocolo HTTP"? É necessário que a pessoa saiba sobre ele? Se sim, vai explicar mesmo que de maneira rápida sobre? Ou então existe algum conteúdo que a pessoa possa consumir para aprender sobre rapidamente? Informe links

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +O mecanismo de roteamento gerencía qual controller recebe quais solicitações.
Correção gramatical: "gerencia"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +Para criar um controller básico utilizamos classes e decorators. os Decorators realizam a função de asociação das classes à metadados necessários que permitem que o Nest crie um mapeamento que vincul
Correção gramatical: "associação", "vincule as"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +No exemplo a seguir usamos o decorator `@Controller()` ele é necessário para definir o controller básico do módulo, nele especificaremos um prefixo de caminho de rota opcional no caso `user`. O prefi
Correção gramatical: "agrupamento", "códigos repetitivos".

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +No exemplo a seguir usamos o decorator `@Controller()` ele é necessário para definir o controller básico do módulo, nele especificaremos um prefixo de caminho de rota opcional no caso `user`. O prefi
Mudança: "evitando a redundância desse prefixo todas às vezes que criarmos uma nova rota."

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +O decorator `@Get()` indica o metodo HTTP que corresponde aquela chamada especifica, indica ao Nest a criação do endpoint no qual corresponde ao metodo HTTP e ao caminho da rota. A rota para um manip
Correção gramatical: "método", "concatenação do prefixo", "qualquer"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +O decorator `@Get()` indica o metodo HTTP que corresponde aquela chamada especifica, indica ao Nest a criação do endpoint no qual corresponde ao metodo HTTP e ao caminho da rota. A rota para um manip
Para evitar muita repetição da frase "método HTTP", você também pode usar às seguintes opções: "verbo HTTP" ou "requisição HTTP"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +O decorator `@Get()` indica o metodo HTTP que corresponde aquela chamada especifica, indica ao Nest a criação do endpoint no qual corresponde ao metodo HTTP e ao caminho da rota. A rota para um manip
Correção gramatical: "PATCH"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +No exemplo como foi declarado um prefixo `user` e não foi adicionado nenhuma informação no caminho do metodo, o Nest mapeará como `GET /user` para cessar o metodo index declarado. Conforme mencionado
Correção gramatical: "método", "acessar", "alguma informação", "caminho, por exemplo:"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +No exemplo quando a solicitação GET é feita para o edpoint, o Nest roteia a solicitação para nosso método definido como `index()`. O nome do método aqui é completamente arbitrário, obviamente é neces
Correção gramatical: "endpoint", "ao nome".

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +Este método retorna um status `200` e a resposta associada, que nesse caso é apena uma string `Essa ação retorna todos os usuários`. Por padrão o Nest trata todo os retornos verificando o tipo, quand
Correção gramatical: "apenas uma", "trata todos", "serializá-lo", "Nest cuida", "disso, ele", "exceto", "métodos"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +Este é o comportamento padrão no nest, mas o framework abre a possibilidade de manipular os métodos e retornos através de bibliotecas especificas configuradas como por exemplo o express que pode ser
Correção gramatical: "Nest", "específicas", "como, por exemplo,", "Express", "manipulação", "Por exemplo,", "com o", "Express"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +Os manipuladores geralmente precisam acessar os detalhes do request do cliente. O Nest fornece acesso ao objeto de solicitação da plataforma subjscente (Express por padrão). Podendo acessar o objeto
Correção gramatical: "subjacente", "Nest", "adicionando"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +O object request representa a solicitação HTTP e tem como propriedades para string de consulta da solicitação, parâmetros, cabeçalhos e corpo. Na maioria dos casos, não é necessário pegar essas propr
Correção gramatical: "específicos"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +| Decorator                | representação                      |
Correção gramatical: "Representação"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +Para compatibilidade com tipagens em plataformas HTTP subjscentes (por exemplo, Express e Fastify), o nest fornece os decorators`@Res()` e `@Response()`. `@Res()` é simplesmente um alias para `@Respo
Correção gramatical: "subjacentes", "Nest", "decorators `@Res()`", "tipagens", "subjacente", "ao máximo", "resposta fazendo"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +É simples assim. O nest fornece decorators para todos os métodos HTTP padrão `@Get()`, `@Post()`, `@Put()`, `@Delete()`, `@Patch()`, `@Options()` e `@Head()`. Além disso, `@All()` define um endpoint
Correção gramatical: "Nest"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +Rotas baseadas em padrões também são suportadas. Por exemplo, o asterisco é usado como curinga e coreponderá a qualquer combinação de caracteres.
Correção gramatical: "corresponderá"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +> Um curinga no meio da rota só é suportado pelo express.
Correção gramatical: "Express"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +Para especificar um cabeçalho de reposta personalizado, pode ser usado o decorator `@Header()` ou um object response específico da biblioteca (e chamar `res.header()` deretamente).
Correção gramatical: "resposta", "diretamente"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +## Parametros de rota
Correção gramatical: "Parâmetros"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +Rotas com caminhos estáticos não funcionarão quando você precisar aceitar dados dinamicos como parte da solicitação (por exemplo, `GET /users/1` para obter usuário com o id `1`). Para definir rotas c
Correção gramatical: "dinâmicos", "parâmetros", "parâmetro", "dinâmico"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +O decorator `@Param()` é usado para capturar os parametros para o método (`params` no exemplo acima), e retorna os parametros de rota disponíveis como propriedades desse parametro de método. Como foi
Correção gramatical: "parâmetros", "código", "pode", "específico"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +O decorator `@Controller` pode ter a opção `host` e exigir que o host HTTP das solicitações recebidas correspondam a algum valor expecifico.
Correção gramatical: "à algum", "específico"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +> Como o Fastify não oferece suporte para roteadores aninhados, o Express deve ser usadi para usar roteamento do subdomínio.
Correção gramatical: "usado"

2024-09-16 12:17 UTC, joaovjo commented on src/content/3-controllers.md
> +Semelhante a uma rota `path`, a opção `hosts` pode usar tokens para capturar o valor dinâmico naquela posição no nome do host. O token de parametro do host no decorator `@Controller()` no exemplo aba
Correção gramatical: "parâmetro"

2024-09-16 12:17 UTC, joaovjo commented on src/images/Controllers_1.png
Fundo branco atrapalha a visualização, trocar para outra cor ou inverter as cores atuais

2024-09-16 21:29 UTC, vgeruso commented on src/content/1-introducao.md
> +O Nest de acordo com a documentação oficial, é um framework para construção de aplicações Node.js do lado do servidor eficientes e escalonáveis. Usando JavaScript progressivo, é construido e possui s
> Informar que NestJS é um framework opinativo

Não entendi essa questão como framework opnativo, poderia me explicar?

2024-09-16 21:58 UTC, vgeruso commented on src/content/1-introducao.md
> +npm i -g @nestjs/cli
Acredito que com o bun ainda não exista suporte, mas irei pesquisar

2024-09-17 00:09 UTC, joaovjo commented on src/content/1-introducao.md
> +O Nest de acordo com a documentação oficial, é um framework para construção de aplicações Node.js do lado do servidor eficientes e escalonáveis. Usando JavaScript progressivo, é construido e possui s
> > Informar que NestJS é um framework opinativo
> 
> Não entendi essa questão como framework opinativo, poderia me explicar?

Como framework opinativo, existem padrões que devem ser fortemente seguidos, o NestJS trás isso do Angular por padrão, até é possível sair dos padrões pré-estabelecidos, mas vai causar dor de cabeça

2024-09-17 14:00 UTC, joaovjo requested changes
Realizar novas correções

2024-09-17 14:00 UTC, joaovjo commented on README.md
> +Contribuições faz com que a comunidade cresca cada vez mais e seja um lugar incrivel para aprender, inspirar e criar. Toda e qualquer tipo de contribuição são **extremamente apreciadas**
Correção gramatical: "cresça", "incrível", "Toda e qualquer contribuição é extremamente apreciada."

2024-09-17 14:00 UTC, joaovjo commented on README.md
> +  Um guia que irá ajudar iniciantes começar a estudar e se aprimorar no framework NestJS.
Correção gramatical: "a começarem", "framework back-end"

2024-09-17 14:00 UTC, joaovjo commented on README.md
> +3. realize o commit (`git coimmit -m 'sua mensagem de commit'`)
Correção gramatical: "Realize"

2024-09-17 14:00 UTC, joaovjo commented on src/content/1-introducao.md
> +O NestJS de acordo com a documentação oficial, é um framework opinativo, ou seja o mesmo conduz a padrões predefinidos, para construção de aplicações Node.js do lado do servidor eficientes e escaloná
Correção gramatical: "construído"

2024-09-17 14:00 UTC, joaovjo commented on src/content/1-introducao.md
> +Por debaixo dos panos, o nosso framework usa como padrão o Express, mas pode ser facilmente configurado para usar o Fastify. Sendo inspirado no framework frontend Angular o NesteJS fornece uma arquit
Correção gramatical: "NestJS fornece"

2024-09-17 14:00 UTC, joaovjo commented on src/content/1-introducao.md
> +1. Conhecimento basico em JavaScript e Node.js
Correção gramatical: "básico"

2024-09-17 14:00 UTC, joaovjo commented on src/content/1-introducao.md
> +npm i -g @nestjs/cli
lgtm

2024-09-17 14:00 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +Para criar uma instância do aplicativo Nest, a classe principal `NestFactory` que expõe métodos estáticos e permitem a criação da instancia do aplicativo. O método `create()` retorna um objeto que pr
Correção gramatical: "instância do aplicativo"

2024-09-17 14:00 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +O sistema irá executar uma transpilação do TypeScript e excutar os endpoints criados imprimindo na tela os ativos:
Correção gramatical: "executar"

2024-09-17 14:00 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +Agora basta acessar em seu navegador ou em algum cliente REST API de sua preferencia o [http://localhost:3000/](http://localhost:3000/), você deverá ver a mensagem `Hello World!` na tela.
Correção gramatical: "preferência"

2024-09-17 14:00 UTC, joaovjo commented on src/content/2-primeiros-passos.md
> +Para Executar a aplicação em modo de obsevação (watch mode) recarregando a mesma após qualquer alteração no código, basta executar `npm start:dev` ou `yarn start:dev` ou `pnpm start:dev` no terminal,
Correção gramatical: "executar", "observação"

2024-09-17 14:00 UTC, joaovjo commented on src/content/3-controllers.md
> +Os controllers são classes responsáveis por receber solicitações e retornar respostas ao cliente atrevés do protocolo `HTTP`.
Correção gramatical: "através"

2024-09-17 14:00 UTC, joaovjo commented on src/content/3-controllers.md
> +O `HTTP` é um protocolo de camada de aplicação que server para comunicação entre navegadores e servidores web, mais detalhes sobre este protocolo recomendo acessar [MDN web docs](https://developer.mo
Correção gramatical: "serve"

2024-09-17 14:00 UTC, joaovjo commented on src/content/3-controllers.md
> +Para criar um controller básico utilizamos classes e decorators. os Decorators realizam a função de associação das classes à metadados necessários que permitem que o Nest crie um mapeamento que vincu
Correção gramatical: "Os decorators", "às solicitações"

2024-09-17 14:00 UTC, joaovjo commented on src/content/3-controllers.md
> +O decorator `@Get()` indica o método HTTP que corresponde aquela chamada especifica, indica ao Nest a criação do endpoint no qual corresponde ao verbo HTTP e ao caminho da rota. A rota para um manipu
Correção gramatical: "específica", "método"

2024-09-17 14:00 UTC, joaovjo commented on src/content/3-controllers.md
> +No exemplo como foi declarado um prefixo `user` e não foi adicionado nenhuma informação no caminho do método, o Nest mapeará como `GET /user` para acessar o metodo index declarado. Conforme mencionad
Correção gramatical: "método"

2024-09-17 14:00 UTC, joaovjo commented on src/content/3-controllers.md
> +Anteriormente, definimos um endpoint para buscar o recurso users (rota `GET`). Normalmente, tembém queremos fornecer um endpoint que crie novos registros. Para isso, vamos criar o manipulador `POST`:
Correção gramatical: "também"

2024-09-17 14:00 UTC, joaovjo commented on src/content/3-controllers.md
> +Para compatibilidade com tipagens em plataformas HTTP subjacentes (por exemplo, Express e Fastify), o Nest fornece os decorators `@Res()` e `@Response()`. `@Res()` é simplesmente um alias para `@Resp
Correção: "subjacente" está com muitas repetições, tente utilizar sinônimos para maior variação

2024-09-17 14:00 UTC, joaovjo commented on src/content/3-controllers.md
> +  console.log(prams.id);
Correção: "params.id"

2024-09-17 14:00 UTC, joaovjo commented on src/content/3-controllers.md
> +Semelhante a uma rota `path`, a opção `hosts` pode usar tokens para capturar o valor dinâmico naquela posição no nome do host. O token de parâmetro do host no decorator `@Controller()` no exemplo aba
Path ou patch?

2024-09-17 23:23 UTC, vgeruso commented on src/content/3-controllers.md
> +Semelhante a uma rota `path`, a opção `hosts` pode usar tokens para capturar o valor dinâmico naquela posição no nome do host. O token de parâmetro do host no decorator `@Controller()` no exemplo aba
Esse é path mesmo kkkk

2024-09-18 00:53 UTC, joaovjo approved these changes
Aprovado

2024-09-18 00:54 UTC, joaovjo approved these changes
Aprovado

2024-09-18 01:28 UTC, merged